// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flreqxttludzexiodmxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZscmVxeHR0bHVkemV4aW9kbXhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzI2MDYsImV4cCI6MjA2NjI0ODYwNn0.f1Z8wERWvU8TJEgyk4x_djRSBfA7KhsLNVmeK58QGmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);